In [ ]:
# prompt: read /content/sample_data/questionnaire_filled_full.csv

import pandas as pd

df = pd.read_csv('/content/sample_data/questionnaire_filled_full.csv')
df.head()

,SchoolID,SchoolName,SchoolType,RespondentID,RespondentType,Gender,Class,B1,B2,B3,...,C4,C5,D1,D2,D3,E1,E2,E3,E4,E5
0,1,Private School A,Private,R001,Student,NaN,NaN,4,3,4,...,4,4,3,4,3,4,4,3,4,3
1,1,Private School A,Private,R002,Student,NaN,NaN,4,4,4,...,3,4,3,4,4,3,4,2,4,4
2,1,Private School A,Private,R003,Student,NaN,NaN,4,3,3,...,2,3,3,4,4,4,3,3,4,4
3,1,Private School A,Private,R004,Student,NaN,NaN,3,4,4,...,3,1,3,3,4,3,1,3,3,4
4,1,Private School A,Private,R005,Student,NaN,NaN,4,4,4,...,4,4,3,4,4,4,4,3,4,4

In [ ]:
# prompt: drop columns with missing value

# Dropping columns with any missing values
df_dropped = df.dropna(axis=1)

print("Original DataFrame shape:", df.shape)
print("DataFrame shape after dropping columns with missing values:", df_dropped.shape)
print(df_dropped.head())

Original DataFrame shape: (148, 28)
DataFrame shape after dropping columns with missing values: (148, 26)
   SchoolID        SchoolName SchoolType RespondentID RespondentType  B1  B2  \
0         1  Private School A    Private         R001        Student   4   3
1         1  Private School A    Private         R002        Student   4   4
2         1  Private School A    Private         R003        Student   4   3
3         1  Private School A    Private         R004        Student   3   4
4         1  Private School A    Private         R005        Student   4   4

   B3  B4  B5  ...  C4  C5  D1  D2  D3  E1  E2  E3  E4  E5
0   4   4   4  ...   4   4   3   4   3   4   4   3   4   3
1   4   3   3  ...   3   4   3   4   4   3   4   2   4   4
2   3   3   3  ...   2   3   3   4   4   4   3   3   4   4
3   4   3   4  ...   3   1   3   3   4   3   1   3   3   4
4   4   4   3  ...   4   4   3   4   4   4   4   3   4   4

[5 rows x 26 columns]

In [ ]:
# prompt: do cronbach

!pip install pingouin
import pingouin as pg

# Assuming df_dropped contains the items for which you want to compute Cronbach's alpha
# Make sure the columns in df_dropped are numeric and represent your scale items.
# If there are non-numeric columns or columns that are not part of the scale, you need to select the relevant columns first.

# Example: Let's assume the first 5 columns of df_dropped are your scale items.
# Replace with the actual column names or indices if needed.
# Selecting only the columns that start with 'B', 'C', 'D', or 'E'
scale_items = df_dropped.filter(regex='^[BCDE]\d+')


cronbach_alpha = pg.cronbach_alpha(data=scale_items)

print("\nCronbach's alpha:")
cronbach_alpha

Requirement already satisfied: pingouin in /usr/local/lib/python3.11/dist-packages (0.5.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from pingouin) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pingouin) (2.0.2)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.11/dist-packages (from pingouin) (2.2.2)
Requirement already satisfied: pandas-flavor in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.7.0)
Requirement already satisfied: scikit-learn>=1.2 in /usr/local/lib/python3.11/dist-packages (from pingouin) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from pingouin) (1.15.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.13.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.14.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5->pingouin) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5->pingouin) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5->pingouin) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.2->pingouin) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.2->pingouin) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (3.2.3)
Requirement already satisfied: xarray in /usr/local/lib/python3.11/dist-packages (from pandas-flavor->pingouin) (2025.3.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels->pingouin) (1.0.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5->pingouin) (1.17.0)

Cronbach's alpha:

(np.float64(0.7514533640816741), array([0.69 , 0.806]))

In [ ]:
df_dropped.head(10)

,SchoolID,SchoolName,SchoolType,RespondentID,RespondentType,B1,B2,B3,B4,B5,...,C4,C5,D1,D2,D3,E1,E2,E3,E4,E5
0,1,Private School A,Private,R001,Student,4,3,4,4,4,...,4,4,3,4,3,4,4,3,4,3
1,1,Private School A,Private,R002,Student,4,4,4,3,3,...,3,4,3,4,4,3,4,2,4,4
2,1,Private School A,Private,R003,Student,4,3,3,3,3,...,2,3,3,4,4,4,3,3,4,4
3,1,Private School A,Private,R004,Student,3,4,4,3,4,...,3,1,3,3,4,3,1,3,3,4
4,1,Private School A,Private,R005,Student,4,4,4,4,3,...,4,4,3,4,4,4,4,3,4,4
5,1,Private School A,Private,R006,Student,3,4,4,3,2,...,4,2,3,4,3,4,2,2,4,3
6,1,Private School A,Private,R007,Student,3,3,4,4,3,...,4,4,3,4,4,4,4,2,4,4
7,1,Private School A,Private,R008,Student,3,4,4,4,4,...,4,4,3,4,4,4,4,3,4,4
8,1,Private School A,Private,R009,Student,2,4,4,3,4,...,2,3,3,3,4,3,3,3,3,4
9,1,Private School A,Private,R010,Student,3,1,4,3,3,...,3,3,3,4,4,3,3,3,4,4

In [ ]:
# prompt:  create mask for private and public school

# Assuming 'school_type' is a column in df_dropped indicating school type
# Replace 'school_type' with the actual column name
# Replace 'Private' and 'Public' with the actual values used in your column

private_school_mask = df_dropped['SchoolType'] == 'Private'
public_school_mask = df_dropped['SchoolType'] == 'Public'

# You can then use these masks to filter the DataFrame:
private_schools_df = df_dropped[private_school_mask]
public_schools_df = df_dropped[public_school_mask]

print("\nDataFrame for Private Schools:")
print(private_schools_df.head())

print("\nDataFrame for Public Schools:")
print(public_schools_df.head())

DataFrame for Private Schools:
   SchoolID        SchoolName SchoolType RespondentID RespondentType  B1  B2  \
0         1  Private School A    Private         R001        Student   4   3
1         1  Private School A    Private         R002        Student   4   4
2         1  Private School A    Private         R003        Student   4   3
3         1  Private School A    Private         R004        Student   3   4
4         1  Private School A    Private         R005        Student   4   4

   B3  B4  B5  ...  C4  C5  D1  D2  D3  E1  E2  E3  E4  E5
0   4   4   4  ...   4   4   3   4   3   4   4   3   4   3
1   4   3   3  ...   3   4   3   4   4   3   4   2   4   4
2   3   3   3  ...   2   3   3   4   4   4   3   3   4   4
3   4   3   4  ...   3   1   3   3   4   3   1   3   3   4
4   4   4   3  ...   4   4   3   4   4   4   4   3   4   4

[5 rows x 26 columns]

DataFrame for Public Schools:
    SchoolID       SchoolName SchoolType RespondentID RespondentType  B1  B2  \
74         3  Public School A     Public         R075        Student   1   1
75         3  Public School A     Public         R076        Student   2   1
76         3  Public School A     Public         R077        Student   1   2
77         3  Public School A     Public         R078        Student   1   4
78         3  Public School A     Public         R079        Student   2   1

    B3  B4  B5  ...  C4  C5  D1  D2  D3  E1  E2  E3  E4  E5
74   1   2   2  ...   3   4   4   3   4   4   2   3   4   4
75   1   3   2  ...   2   2   4   3   4   3   3   3   3   4
76   1   3   1  ...   3   2   3   4   3   4   4   3   4   3
77   3   2   2  ...   2   4   3   4   4   3   4   3   4   4
78   1   3   3  ...   3   2   4   3   4   4   3   3   4   4

[5 rows x 26 columns]

In [ ]:
# prompt: for each of b1, b2......E5 find mean  and standard deviation for public , private

# Selecting the relevant columns for analysis
items_to_analyze = df_dropped.filter(regex='^[BCDE]\d+')

# Calculating mean and standard deviation for private schools
private_stats = private_schools_df[items_to_analyze.columns].agg(['mean', 'std']).T
private_stats = private_stats.rename(columns={'mean': 'Private_Mean', 'std': 'Private_StdDev'})

# Calculating mean and standard deviation for public schools
public_stats = public_schools_df[items_to_analyze.columns].agg(['mean', 'std']).T
public_stats = public_stats.rename(columns={'mean': 'Public_Mean', 'std': 'Public_StdDev'})

# Combining the statistics into a single DataFrame for comparison
comparison_stats = private_stats.join(public_stats)

print("\nMean and Standard Deviation by School Type for Items B1-E5:")
comparison_stats

Mean and Standard Deviation by School Type for Items B1-E5:

    Private_Mean  Private_StdDev  Public_Mean  Public_StdDev
B1      3.324324        0.742231     2.054054       0.825815
B2      3.310811        0.775051     2.000000       0.891359
B3      3.418919        0.641205     1.972973       0.935934
B4      3.256757        0.642359     2.256757       0.980087
B5      3.364865        0.673863     2.027027       0.921181
B6      3.297297        0.735215     2.243243       0.933557
B7      3.554054        0.552501     2.094595       0.967541
B8      3.270270        0.763864     2.067568       0.955605
C1      3.283784        0.767852     2.459459       1.036184
C2      3.162162        0.844434     2.648649       0.999074
C3      3.040541        0.766404     2.418919       1.033769
C4      3.256757        0.722644     2.554054       1.035558
C5      3.027027        0.935934     2.472973       1.062731
D1      3.216216        0.414473     3.459459       0.501756
D2      3.608108        0.491505     3.472973       0.502677
D3      3.797297        0.404757     3.797297       0.404757
E1      3.581081        0.596950     3.581081       0.596950
E2      3.216216        0.895503     3.445946       0.778863
E3      2.864865        0.344201     2.972973       0.163269
E4      3.783784        0.414473     3.770270       0.423530
E5      3.783784        0.414473     3.783784       0.414473

In [ ]:
# prompt: from df_dropped find average of all B for each row and all c for each row, do corellatio and regression for public, private, combined

# Find average of all B for each row
df_dropped['Avg_B'] = df_dropped.filter(regex='^B\d+').mean(axis=1)

# Find average of all C for each row
df_dropped['Avg_C'] = df_dropped.filter(regex='^C\d+').mean(axis=1)

# Recreate private and public school dataframes after adding the new columns
private_school_mask = df_dropped['SchoolType'] == 'Private'
public_school_mask = df_dropped['SchoolType'] == 'Public'

private_schools_df = df_dropped[private_school_mask]
public_schools_df = df_dropped[public_school_mask]


# Print the first few rows to show the new columns
print("\nDataFrame with Avg_B and Avg_C:")
print(df_dropped[['Avg_B', 'Avg_C']].head())

# Correlation for combined data
combined_correlation = df_dropped[['Avg_B', 'Avg_C']].corr()
print("\nCorrelation between Avg_B and Avg_C for Combined Data:")
print(combined_correlation)

# Correlation for private schools
private_correlation = private_schools_df[['Avg_B', 'Avg_C']].corr()
print("\nCorrelation between Avg_B and Avg_C for Private Schools:")
print(private_correlation)

# Correlation for public schools
public_correlation = public_schools_df[['Avg_B', 'Avg_C']].corr()
print("\nCorrelation between Avg_B and Avg_C for Public Schools:")
print(public_correlation)

# Regression for combined data (Avg_C as dependent, Avg_B as independent)
# Need statsmodels for regression
!pip install statsmodels
import statsmodels.api as sm

X_combined = df_dropped['Avg_B']
y_combined = df_dropped['Avg_C']
X_combined = sm.add_constant(X_combined) # Add a constant for the intercept
model_combined = sm.OLS(y_combined, X_combined).fit()
print("\nRegression Results for Combined Data (Avg_C ~ Avg_B):")
print(model_combined.summary())

# Regression for private schools
X_private = private_schools_df['Avg_B']
y_private = private_schools_df['Avg_C']
X_private = sm.add_constant(X_private)
model_private = sm.OLS(y_private, X_private).fit()
print("\nRegression Results for Private Schools (Avg_C ~ Avg_B):")
print(model_private.summary())

# Regression for public schools
X_public = public_schools_df['Avg_B']
y_public = public_schools_df['Avg_C']
X_public = sm.add_constant(X_public)
model_public = sm.OLS(y_public, X_public).fit()
print("\nRegression Results for Public Schools (Avg_C ~ Avg_B):")
print(model_public.summary())

DataFrame with Avg_B and Avg_C:
   Avg_B  Avg_C
0  3.625    3.2
1  3.750    3.4
2  3.375    2.8
3  3.500    2.8
4  3.625    3.4

Correlation between Avg_B and Avg_C for Combined Data:
          Avg_B     Avg_C
Avg_B  1.000000  0.551533
Avg_C  0.551533  1.000000

Correlation between Avg_B and Avg_C for Private Schools:
          Avg_B     Avg_C
Avg_B  1.000000 -0.227987
Avg_C -0.227987  1.000000

Correlation between Avg_B and Avg_C for Public Schools:
         Avg_B    Avg_C
Avg_B  1.00000  0.10798
Avg_C  0.10798  1.00000
Requirement already satisfied: statsmodels in /usr/local/lib/python3.11/dist-packages (0.14.4)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from statsmodels) (2.0.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.11/dist-packages (from statsmodels) (1.15.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /usr/local/lib/python3.11/dist-packages (from statsmodels) (2.2.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.11/dist-packages (from statsmodels) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

Regression Results for Combined Data (Avg_C ~ Avg_B):
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Avg_C   R-squared:                       0.304
Model:                            OLS   Adj. R-squared:                  0.299
Method:                 Least Squares   F-statistic:                     63.83
Date:                Mon, 07 Jul 2025   Prob (F-statistic):           3.74e-13
Time:                        20:54:06   Log-Likelihood:                -88.973
No. Observations:                 148   AIC:                             181.9
Df Residuals:                     146   BIC:                             187.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.6769      0.149     11.241      0.000       1.382       1.972
Avg_B          0.4249      0.053      7.989      0.000       0.320       0.530
==============================================================================
Omnibus:                        1.250   Durbin-Watson:                   2.056
Prob(Omnibus):                  0.535   Jarque-Bera (JB):                1.333
Skew:                          -0.207   Prob(JB):                        0.514
Kurtosis:                       2.789   Cond. No.                         12.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Regression Results for Private Schools (Avg_C ~ Avg_B):
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Avg_C   R-squared:                       0.052
Model:                            OLS   Adj. R-squared:                  0.039
Method:                 Least Squares   F-statistic:                     3.948
Date:                Mon, 07 Jul 2025   Prob (F-statistic):             0.0507
Time:                        20:54:06   Log-Likelihood:                -25.089
No. Observations:                  74   AIC:                             54.18
Df Residuals:                      72   BIC:                             58.79
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.2269      0.541      7.806      0.000       3.148       5.306
Avg_B         -0.3203      0.161     -1.987      0.051      -0.642       0.001
==============================================================================
Omnibus:                        7.631   Durbin-Watson:                   1.622
Prob(Omnibus):                  0.022   Jarque-Bera (JB):                7.299
Skew:                          -0.599   Prob(JB):                       0.0260
Kurtosis:                       3.966   Cond. No.                         49.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Regression Results for Public Schools (Avg_C ~ Avg_B):
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Avg_C   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                    0.8494
Date:                Mon, 07 Jul 2025   Prob (F-statistic):              0.360
Time:                        20:54:06   Log-Likelihood:                -50.431
No. Observations:                  74   AIC:                             104.9
Df Residuals:                      72   BIC:                             109.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.1450      0.401      5.350      0.000       1.346       2.944
Avg_B          0.1751      0.190      0.922      0.360      -0.204       0.554
==============================================================================
Omnibus:                        1.576   Durbin-Watson:                   2.049
Prob(Omnibus):                  0.455   Jarque-Bera (JB):                1.359
Skew:                          -0.172   Prob(JB):                        0.507
Kurtosis:                       2.432   Cond. No.                         18.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
# prompt: average and s.d for d for public , private

# Find average of all D for each row
df_dropped['Avg_D'] = df_dropped.filter(regex='^D\d+').mean(axis=1)

# Recreate private and public school dataframes after adding the new columns
private_school_mask = df_dropped['SchoolType'] == 'Private'
public_school_mask = df_dropped['SchoolType'] == 'Public'

private_schools_df = df_dropped[private_school_mask]
public_schools_df = df_dropped[public_school_mask]

# Calculating mean and standard deviation for Avg_D for private schools
private_d_stats = private_schools_df['Avg_D'].agg(['mean', 'std']).T
private_d_stats = private_d_stats.rename({'mean': 'Private_Avg_D_Mean', 'std': 'Private_Avg_D_StdDev'})

# Calculating mean and standard deviation for Avg_D for public schools
public_d_stats = public_schools_df['Avg_D'].agg(['mean', 'std']).T
public_d_stats = public_d_stats.rename({'mean': 'Public_Avg_D_Mean', 'std': 'Public_Avg_D_StdDev'})

print("\nAverage and Standard Deviation for Avg_D by School Type:")
print(private_d_stats)
public_d_stats

Average and Standard Deviation for Avg_D by School Type:
Private_Avg_D_Mean      3.540541
Private_Avg_D_StdDev    0.162764
Name: Avg_D, dtype: float64

Public_Avg_D_Mean      3.576577
Public_Avg_D_StdDev    0.149044
Name: Avg_D, dtype: float64

In [ ]:
# prompt: welch t_test , one tail if possible to compare c in public and private

# Perform Welch's t-test comparing 'Avg_C' between public and private schools
# A one-tailed test checks if the mean of one group is significantly greater (or less) than the mean of the other.
# Let's assume we want to test if the mean of Avg_C is *different* in private vs public schools (two-tailed).
# If you need a one-tailed test (e.g., checking if private > public or private < public), you would adjust the `alternative` parameter.
# 'two-sided' is the default. Use 'greater' or 'less' for one-tailed tests.

# Example for a two-sided test (checking for a difference):
ttest_result_c_two_sided = pg.ttest(private_schools_df['Avg_C'], public_schools_df['Avg_C'], correction=True, alternative='two-sided')

print("\nWelch's t-test comparing Avg_C between Private and Public Schools (Two-sided):")
print(ttest_result_c_two_sided)

# Example for a one-sided test (checking if Private Avg_C is greater than Public Avg_C):
ttest_result_c_greater = pg.ttest(private_schools_df['Avg_C'], public_schools_df['Avg_C'], correction=True, alternative='greater')

print("\nWelch's t-test comparing Avg_C between Private and Public Schools (One-sided: Private > Public):")
print(ttest_result_c_greater)

# Example for a one-sided test (checking if Private Avg_C is less than Public Avg_C):
ttest_result_c_less = pg.ttest(private_schools_df['Avg_C'], public_schools_df['Avg_C'], correction=True, alternative='less')

print("\nWelch's t-test comparing Avg_C between Private and Public Schools (One-sided: Private < Public):")
ttest_result_c_less

Welch's t-test comparing Avg_C between Private and Public Schools (Two-sided):
               T         dof alternative         p-val         CI95%  \
T-test  9.247837  133.125431   two-sided  4.951503e-16  [0.51, 0.78]

         cohen-d       BF10  power
T-test  1.520335  1.767e+13    1.0

Welch's t-test comparing Avg_C between Private and Public Schools (One-sided: Private > Public):
               T         dof alternative         p-val        CI95%   cohen-d  \
T-test  9.247837  133.125431     greater  2.475752e-16  [0.53, inf]  1.520335

             BF10  power
T-test  3.535e+13    1.0

Welch's t-test comparing Avg_C between Private and Public Schools (One-sided: Private < Public):

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,9.247837,133.125431,less,1.0,"[-inf, 0.76]",1.520335,2.829e-14,1.106701e-27

In [ ]:
# prompt: repeat but for B

# Perform Welch's t-test comparing 'Avg_B' between public and private schools
# Using a two-tailed test as an example:
ttest_result_b_two_sided = pg.ttest(private_schools_df['Avg_B'], public_schools_df['Avg_B'], correction=True, alternative='two-sided')

print("\nWelch's t-test comparing Avg_B between Private and Public Schools (Two-sided):")
print(ttest_result_b_two_sided)

# Example for a one-sided test (checking if Private Avg_B is greater than Public Avg_B):
ttest_result_b_greater = pg.ttest(private_schools_df['Avg_B'], public_schools_df['Avg_B'], correction=True, alternative='greater')

print("\nWelch's t-test comparing Avg_B between Private and Public Schools (One-sided: Private > Public):")
print(ttest_result_b_greater)

# Example for a one-sided test (checking if Private Avg_B is less than Public Avg_B):
ttest_result_b_less = pg.ttest(private_schools_df['Avg_B'], public_schools_df['Avg_B'], correction=True, alternative='less')

print("\nWelch's t-test comparing Avg_B between Private and Public Schools (One-sided: Private < Public):")
ttest_result_b_less

Welch's t-test comparing Avg_B between Private and Public Schools (Two-sided):
                T         dof alternative         p-val         CI95%  \
T-test  27.826673  141.593103   two-sided  2.875657e-59  [1.17, 1.35]

         cohen-d       BF10  power
T-test  4.574677  2.573e+56    1.0

Welch's t-test comparing Avg_B between Private and Public Schools (One-sided: Private > Public):
                T         dof alternative         p-val        CI95%  \
T-test  27.826673  141.593103     greater  1.437829e-59  [1.19, inf]

         cohen-d       BF10  power
T-test  4.574677  5.145e+56    1.0

Welch's t-test comparing Avg_B between Private and Public Schools (One-sided: Private < Public):

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,27.826673,141.593103,less,1.0,"[-inf, 1.34]",4.574677,1.943e-57,2.477763e-163

In [ ]:
# prompt: number of teachers and stuents and vp.... for public and private

import pandas as pd
# Assuming 'Role' is a column in df_dropped indicating the role (e.g., 'Teacher', 'Student', 'VP')
# Replace 'Role' with the actual column name
# Replace 'Teacher', 'Student', 'VP' with the actual values used in your column

# Count roles for private schools
private_role_counts = private_schools_df['RespondentType'].value_counts()

# Count roles for public schools
public_role_counts = public_schools_df['RespondentType'].value_counts()

print("\nRole Counts for Private Schools:")
print(private_role_counts)

print("\nRole Counts for Public Schools:")
print(public_role_counts)

# To combine these into a single table for easier comparison:
role_comparison_df = pd.DataFrame({'Private': private_role_counts, 'Public': public_role_counts}).fillna(0).astype(int)

print("\nComparison of Role Counts by School Type:")
role_comparison_df

Role Counts for Private Schools:
RespondentType
Student           50
Teacher           20
Vice Principal     2
Principal          2
Name: count, dtype: int64

Role Counts for Public Schools:
RespondentType
Student           50
Teacher           20
Vice Principal     2
Principal          2
Name: count, dtype: int64

Comparison of Role Counts by School Type:

                Private  Public
RespondentType
Student              50      50
Teacher              20      20
Vice Principal        2       2
Principal             2       2